spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: gallery-service-gw
          uri: http://localhost:8100
          predicates:
            - Path=/gallery/**

eureka:
  client:
    register-with-eureka: true
    fecth-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost
